"""modified id of user to uuid

Revision ID: 6f92694f86b0
Revises: 
Create Date: 2025-10-21 21:13:47.910528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f92694f86b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('verified_acc', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_table('Senior',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seniorName', sa.String(), nullable=False),
    sa.Column('seniorEmail', sa.String(), nullable=False),
    sa.Column('buddy1', sa.String(), nullable=False),
    sa.Column('buddy1Email', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Checkin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('senior_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('senior_checked', sa.Boolean(), nullable=True),
    sa.Column('buddy_checked', sa.Boolean(), nullable=True),
    sa.Column('buddy_notified', sa.Boolean(), nullable=True),
    sa.Column('user_notified', sa.Boolean(), nullable=True),
    sa.Column('buddy_email', sa.String(), nullable=False),
    sa.Column('notification_sent', sa.DateTime(timezone=True), nullable=True),
    sa.Column('senior_acked_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('buddy_acked_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['senior_id'], ['Senior.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Checkin')
    op.drop_table('Senior')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
